########################################################
#
#         PRIVATE TALK
#   "The ultimate chat solution"
#
# Having issues? Contact me on discord @ Perotin#3447


command-name: "privatetalk"
aliases:
   - "pt"
   - "chatrooms"


saved-material: "OAK_SIGN"

quickchat-prefix: "@"

chatroom-message-format: "&7[&e$chatroom$&7] &e$role$ &7$name$ ➤ &e$message$"
bungeecord: false

