########################################################
#
#         PRIVATE TALK
#   "The ultimate chat solution"
#
# Having issues? Contact me on discord @ Perotin#3447

#note most of the configuration comes in menus.yml / messages.yml!

# Should chat colors be allowed throughout the plugin? (chatroom names, player statuses, etc.)
chat-colors: true
command-name: "playerchannels"
aliases:
   - "pc"
   - "chatrooms"
   - "channels"


saved-material: "OAK_SIGN"

quickchat-prefix: "@"

# If $nickname$ is present, will use the player's chatroom nickname
# if it exists, other will just use their minecraft name
# Valid placeholders for this:
# $role$ - Role in chatroom (e.g. Member, Moderator, Owner, values defined in messages.yml)
# $chatroom$ - Name of chatroom message is being sent in
# $nickname$ - Nickname of player in chatroom, if player does not have a nickname or it is disabled will just default to $name$
# $name$ - Real minecraft name of plaeyer

chatroom-message-format: "&7[&e$chatroom$&7] &e$role$ $nickname$ &7➤ &e$message$"
bungeecord: false

