########################################################
#
#      𝓟𝓻𝓲𝓿𝓪𝓽𝓮𝓣𝓪𝓵𝓴
#   "The ultimate chat solution"
#
# Having issues? Contact me on discord @ Perotin#3447


command-name: "privatetalk"
alias:
   - "pt"
   - "chatrooms"