########################################################
#
#         PRIVATE TALK
#   "The ultimate chat solution"
#
# Having issues? Contact me on discord @ Perotin#3447


command-name: "privatetalk"
aliases:
   - "pt"
   - "chatrooms"


saved-material: "OAK_SIGN"
