name: PlayerChannels
main: me.perotin.playerchannels.PlayerChannels
author: Perotin
version: 3.7.4
api-version: 1.14
description: The ultimate chat channels solution.
commands:
  playerchannels:
    usage: /playerchannels
    aliases: [channels, pc, chatrooms]
  pcadmin:
    permission: playerchannels.admin
    usage: /pcadmin
    aliases: [pca]
    description: Admin commands

