name: PlayerChannels
main: me.perotin.playerchannels.PlayerChannels
author: Perotin
version: 3.4.3
api-version: 1.14
description: The ultimate chatroom solution.
depends: UltimateAdvancementAPI
commands:
  pcadmin:
    permission: playerchannels.admin
    usage: /pcadmin
    aliases: /pca
    description: Admin commands

